import type { Metadata } from 'next'
import { Montserrat, Oxanium } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/contexts/auth-context'
import { ReactQueryProvider } from '@providers'
import { ToastContainer } from 'react-toastify'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const oxanium = Oxanium({
  weight: ['500', '600'],
  subsets: ['latin-ext'],
  variable: '--font-oxinium',
})
const montserrat = Montserrat({
  weight: ['500', '600'],
  subsets: ['latin-ext'],
  variable: '--font-montserrat',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="bg-blue-dark  text-gray-100   md:bg-right-top bg-top">
        <main>
          <ReactQueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </ReactQueryProvider>
          <ToastContainer />
        </main>
      </body>
    </html>
  )
}
